refactor(types): consolidate declaration files
- remove ambient declaration file (which was a hack to get around
importing types with `@import` and running into error TS9006 for some
reason)
- remove `types.d.ts` and rename `internal.d.ts` to `types.d.ts`